### ISSUE TITLE
ERROR in ./node_modules/storybook-addon-angularjs/utils/angularjs.js Module not found: Error: Can't resolve 'angular'

### ISSUE THREAD

**Issue by mohaiminalaoun** [titonobre/storybook-addon-angularjs#17]
I have installed storybook for html, and the example from the Offical page works.

However, I tried installing storybook-addon-angularjs and this is the error I get.

```
ERROR in ./node_modules/storybook-addon-angularjs/decorator.js
Module not found: Error: Can't resolve 'angular' in 'C:\Users\mohaimin.alaoun\Documents\Company\studio\trunk\webapps\DF\node_modules\storybook-addon-angularjs'
```

Any idea how I can fix this?

Note: using this in an existing angularjs app.

**Comment by titonobre** [comment]
Hi @mohaiminalaoun 

Have you checked the [example in this repository](https://github.com/titonobre/storybook-addon-angularjs/tree/master/example)? It contains the bare minimum you need to use the addon plus a few integrations with other addons.

Also, this addon has a couple of [peer dependencies](https://github.com/titonobre/storybook-addon-angularjs/blob/master/lib/package.json#L13) that should be provided by your project. Maybe I should update the README to mention this.

Please let me know if this fixed your problem.

**Comment by mohaiminalaoun** [comment]
@titonobre Yes, thank you. Installing the peer dependencies myself separately fixed this issue.
