### ISSUE TITLE
No interpolation possible when input type is '@'

### ISSUE THREAD

**Issue by pmachaux** [titonobre/storybook-addon-angularjs#2]
Hi,

Thanks for your great addon. I faced an issue where interpolation was not working for primitive input.
After debugging I noticed that the issue comes from the processTemplate function.

I locally solved it like this by passing the value directly instead of the prop construction when the variable for the interpolation is a direct string.

function processTemplate(strings, ...values) {
  return strings.reduce(
    (acc, str, i) => {
      const prop = i < values.length ? "_prop" + i : "";
      const templateToAdd = typeof values[i] === "string" ? values[i] : prop;
      acc.template += str + templateToAdd;
      if (i < values.length) {
        acc.scope[prop] = values[i];
      }
      return acc;
    },
    { template: "", scope: {} }
  );
}

What do you think about it ? I tested it and did not observe any issue.
Would you like me to do a PR for this ?

Thanks for your help,

**Comment by titonobre** [comment]
Hi @pmachaux. Thank you for using this.

I've updated the example project with [the solution I use](https://github.com/titonobre/storybook-addon-angularjs-example/compare/41f8403ec498a8c2447017dd24a55aaef3c75969..07527803d731cfeae89ab8c79f09ddce55301158). 

Can you please check if it fits your needs?

**Comment by pmachaux** [comment]
It works great.
Thanks a lot for your help !

Have a nice day and thanks again for the awesome work !
