### ISSUE TITLE
Transclusion doesn't seem to work within stories.

### ISSUE THREAD

**Issue by jhummel** [titonobre/storybook-addon-angularjs#3]
It seems tranclusion doesn't work within stories. If I do something like:

    <my-component>
      <my-transclusion-element>This should get transcluded to the correct spot</my-transclusion-element>
    </my-component>

It doesn't put the content in the correct spot. It just outputs the same markup as above. I'm just using regular ol' `ng-transclude` to put the content in the correct place. It might be that return function of the`$compile` call, may need a transclusion function.

**Comment by titonobre** [comment]
Hi.

I've added a new branch [`demos-with-transclusion`](https://github.com/titonobre/storybook-addon-angularjs-example/tree/demos-with-transclusion)   to the repository [storybook-addon-angularjs-example](https://github.com/titonobre/storybook-addon-angularjs-example) with some examples with transclusion.

See the changes here: https://github.com/titonobre/storybook-addon-angularjs-example/commit/2cfa1435bce2e1728ce840716d89d45957f645eb

Please let me know if this helps solving your problem. If it doesn't, can you share an example so I can work this on?

**Comment by jhummel** [comment]
Ugh. I'm an idiot. Misconfiguration on my part. Everything is working as intended. Thanks!
