### ISSUE TITLE
Improvements not published to npm

### ISSUE THREAD

**Issue by ofhouse** [titonobre/storybook-addon-angularjs#8]
Hi,

just a short heads up, that the latest published version `0.1.1` does not contain the recent changes from master:
https://unpkg.com/browse/storybook-addon-angularjs@0.1.1/lib/index.js

It only contains the legacy `forModule` syntax.

**Comment by titonobre** [comment]
This release was done before the latest changes in master.
I created another [branch for release 0.1 ](https://github.com/titonobre/storybook-addon-angularjs/tree/release/v0.1).

Very soon I will publish from master with version 1.0. I just need to run some tests before with a real component library using this addon to make sure I didn't broke anything.

**Comment by ofhouse** [comment]
Thanks for the response.
Okay, missed to lookup for the branch, so I thought it was not published by mistake 🤗.
I already use it with a local checkout to create stories for an internal app and did not encounter any errors so far, really enjoying the new syntax 👌
Looking forward for the release!
